name: ios-test-build
# Trigger on push to dtv-sync branch
on:
  push:
    branches:
      - dtv-sync
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      - name: Build iOS IPA
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      - name: Create unsigned IPA
        run: |
          cd simple_live_app
          mkdir -p build/ios/iphoneos/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos/
          zip -q -r SimpleLive_dtv_sync.ipa Payload

      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned
          path: |
            simple_live_app/build/ios/iphoneos/SimpleLive_dtv_sync.ipa
